baseURL = 'https://mint-system.ch/'
languageCode = 'de-CH'
title = 'Mint System'
draft = false

defaultContentLanguage = "de"    
defaultContentLanguageInSubdir = false

[pagination]
  disableAliases = false
  pagerSize = 12
  path = ''

[languages]
[languages.de]
languageName = "Deutsch"
weight = 1
contentDir = "content/de"

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"

[permalinks]
blog = "/blog/:slug/"

[params]
description = "Your site description."
author = "Your Name"
default_image = "/images/default-social-image.jpg"
logo = "/images/logo.png"
twitter_username = "@yourTwitterHandle"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]

[taxonomies]
tag = "tags"
category = "categories"
