[permalinks]
blog = "/blog/:slug/"

[params]
description = "Your site description."
author = "Your Name"
default_image = "/images/default-social-image.jpg"
logo = "/images/logo.png"
twitter_username = "@yourTwitterHandle"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]

[taxonomies]
tag = "tags"
category = "categories"



[languages]
  [languages.de]
    contentDir = 'content/'
    languageCode = 'de-DE'
    languageDirection = 'ltr'
    languageName = 'Deutsch'
    weight = 2
    [languages.de.pagination]
      disableAliases = true
      pagerSize = 12
      path = 'blatt'