baseURL = 'http://localhost:1313/'
languageCode = 'de-DE'
title = 'Mint System'
draft = false
publishDir = "public"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableKinds = ['rss', 'xml']

[pagination]
disableAliases = false
pagination = 12
pagerSize = 12
path = ''

[languages]
[languages.de]
languageCode = 'de-DE'
languageName = "Deutsch"
weight = 1
contentDir = "content/de"

[languages.de.params]
dateFormat = "2. January 2006"

[languages.de.pagination]
disableAliases = true
pagerSize = 12
path = ''

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"

[languages.en.pagination]
disableAliases = true
pagerSize = 12
path = ''

[permalinks]
blog = "/blog/:slug/"
jobs = "/jobs/:slug/"

[params]
description = ""
author = "Mint System"
default_image = "/assets/logos/Logo-Mint-final.svg"
logo = "/assets/logos/Logo-Mint-final.svg"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]


[build]
writeStats = true

[minify]
disableHTML = false
disableCSS = false
disableJS = false
disableSVG = false


[[headers]]
for = "/*"
[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"


[imaging]
  quality = 85
  hint = "photo"