# baseURL = 'https://hugo-starter-murex.vercel.app/'
baseURL = 'http://localhost:1313/'
languageCode = 'de-DE'
title = 'Mint System'
draft = false

defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
paginate = 12

[pagination]
disableAliases = false
pagination = 5
pagerSize = 12
path = ''

[languages]
[languages.de]
languageCode = 'de-DE'
languageName = "Deutsch"
weight = 1
contentDir = "content/de"
[languages.de.pagination]
disableAliases = true
pagerSize = 12
path = ''

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"
[languages.en.pagination]
disableAliases = true
pagerSize = 12
path = ''

[permalinks]
blog = "/blog/:slug/"
jobs = "/jobs/:slug/"

[params]
description = "Your site description."
author = "Your Name"
default_image = "/images/default-social-image.jpg"
logo = "/images/logo.png"
twitter_username = "@yourTwitterHandle"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML"]
page = ["HTML"]
section = ["HTML"]

[taxonomies]
tag = "tags"
category = "categories"
