[permalinks]
blog = "/blog/:slug/"

[params]
description = "Your site description."
author = "Your Name"
default_image = "/images/default-social-image.jpg"
logo = "/images/logo.png"
twitter_username = "@yourTwitterHandle"

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
