baseURL = 'https://mint-system.ch/'
languageCode = 'de-CH'
title = 'Mint System'
draft = false

defaultContentLanguage = "de"  # Set German as default language
defaultContentLanguageInSubdir = true  # Create subdirectories for each language

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de" 

  [languages.en]
    languageName = "English"
    weight = 2
    contentDir = "content/en" 